services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    dev_vita_bundle:
        class: 'Bits\DevVitaBundle\DevVitaBundle'
        public: true
        
    Bits\DevVitaBundle\Controller\:
        resource: '../src/Controller' # Pfad relativ zur services.yaml
        tags: ['controller.service_arguments']
        autowire: true
        autoconfigure: true
        
    Bits\DevVitaBundle\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

   